adminWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
   # path('', include(('tablelist.urls', 'tablelist'), namespace='tablelist')),
]

home/urls.py
from django.urls import path, include

from . import views
app_name = 'home'
urlpatterns = [
    path('', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('home', views.home, name="home"),
    path('home/user/<int:people_id>/', views.detailUser, name='detail'),
    path('home/update/<int:people_id>/', views.updateUser, name='update'),
    path('home/delete/<int:people_id>/', views.deleteUser, name='delete'),
    path('home/search/', views.searchUser, name='search'),
    path('home/tablelist', views.listUser, name='tablelist'),
    path('home/notification', views.listNotification, name='notification'),
    path('home/statistical', views.statistical, name='statistical')

   # path('user/<int:people_id>', UpdateUser.as_view(), name='update'),
]

templates/tablelist/index.html
{% extends 'home/base.html'%} {% load static%} {% block sidebarblock%}
<div class="sidebar-wrapper">
  <ul class="nav">
    <li>
      <a href="{% url 'home:statistical' %}">
        <i class="nc-icon nc-bank"></i>
        <p>Thống kê</p>
      </a>
    </li>
    <li>
      <a href="{% url 'home:notification' %}">
        <i class="nc-icon nc-bell-55"></i>
        <p>Lịch sử</p>
      </a>
    </li>
    <li>
      <a href="{% url 'home:detail' request.session.people_id %}">
        <i class="nc-icon nc-single-02"></i>
        <p>Thông tin người dùng</p>
      </a>
    </li>
    {% if request.session.role_id == 1 %}
    <li class="active">
      <a href="{% url 'home:tablelist' %}">
        <i class="nc-icon nc-tile-56"></i>
        <p>Người dùng</p>
      </a>
    </li>
    {% endif%}
  </ul>
</div>
{% endblock %} {% block contentblock%}

<!--   Content   -->
<div class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">User</h4>

          <form method="post" action="{% url 'home:search' %}">
            {% csrf_token %}
            <div style="width: 40%" class="input-group no-border">
              <input type="text" name="strSearch" value="" class="form-control" placeholder="Search..." />
              <div class="input-group-append">
                <div class="input-group-text">
                  <button type="submit" class="btn btn-primary btn-round">
                    <i class="nc-icon nc-zoom-split"></i>
                  </button>
                </div>
              </div>
            </div>
          </form>
        </div>

        <div class="card-body">
          <div class="table-responsive">
            <table class="table">
              <thead class="text-primary">
                <th>ID</th>
                <th>Tên</th>
                <th>Tuổi</th>
                <th>Giới tính</th>
                <th>Loại tài khoản</th>
                <th>Ảnh</th>
              </thead>
              <tbody>
                {% for item in people%}
                <tr>
                  <td>{{item.ID}}</td>
                  <td>{{item.Name}}</td>
                  <td>{{item.Age}}</td>
                  <td>{% if item.Gender == 1 %} Nam {% else %} Nữ {%endif%}</td>
                  <td>{% if item.RoleID == 1 %} Admin {% else %} User {%endif%}</td>
                  <td>
                    <div>
                      <!-- <img src="{% static item.get_url_image %}" style="height: 150px; width: 190px" alt="" /> -->

                      <img src="data:image/png;base64,{{item.image}}" style="height: 150px; width: 190px" alt="" />
                    </div>
                  </td>
                  <td>
                    <a href="{% url 'home:detail' item.ID %}">Sửa</a>
                  </td>
                  <td>
                    <a href="{% url 'home:delete' item.ID %}">Xóa</a>
                  </td>
                </tr>
                {% endfor%}
              </tbody>
            </table>
            <div class="pagination" style="dipslay: flex; justify-content: center">
              <span class="step-links">
                {% if people.has_previous %}
                <a href="?page=1">&laquo; First</a>
                <a href="?page={{ people.previous_page_number }}">Previous</a>
                {% endif %}

                <span class="current"> Page {{ people.number }} of {{ people.paginator.num_pages }}. </span>

                {% if people.has_next %}
                <a href="?page={{ people.next_page_number }}">Next</a>
                <a href="?page={{ people.paginator.num_pages }}">Last &raquo;</a>
                {% endif %}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End Content -->

{% endblock %}