adminWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
   # path('', include(('tablelist.urls', 'tablelist'), namespace='tablelist')),
]

home/urls.py
from django.urls import path, include

from . import views
app_name = 'home'
urlpatterns = [
    path('', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('home', views.home, name="home"),
    path('home/user/<int:people_id>/', views.detailUser, name='detail'),
    path('home/update/<int:people_id>/', views.updateUser, name='update'),
    path('home/delete/<int:people_id>/', views.deleteUser, name='delete'),
    path('home/search/', views.searchUser, name='search'),
    path('home/tablelist', views.listUser, name='tablelist'),
    path('home/notification', views.listNotification, name='notification'),
    path('home/statistical', views.statistical, name='statistical')

   # path('user/<int:people_id>', UpdateUser.as_view(), name='update'),
]

home/models.py
import base64
import datetime

from django.db import models
from matplotlib import image
# Create your models here.
class People(models.Model):
    ID = models.IntegerField(primary_key=True, null=False, default=0)
    Name = models.CharField(max_length=100,null=True)
    Age = models.IntegerField(null=True)
    Gender = models.IntegerField(null=True)
    RFID = models.CharField(max_length=15,null=True)
    RoleID = models.IntegerField(null=True)
    image = models.TextField(null=True)

    def get_url_image(self):
        return "img/dataset/" +str(self.ID) + "/User." + str(self.ID) +'.1' +".jpg"

    def get_image(self):
        return str(self.image)

class Account(models.Model):
    people = models.OneToOneField(
        People,
        on_delete=models.CASCADE,
        primary_key=True,
        )
    UserName = models.CharField(max_length=100,null=False)
    Password = models.CharField(max_length=100,null=False)


class CheckPeople(models.Model):
    checkpeople = models.IntegerField(null=True,default=0)
    ok = models.IntegerField(null=True,default=0)
    id_check = models.IntegerField(default=0)
    time = models.DateTimeField(null=False, default=datetime.datetime.now())
    image = models.TextField(null=True)


    def decode_image(self):
        return self.image.decode('utf-8')   

home/views.py
import sqlite3


from django.shortcuts import render
from django.core.paginator import Paginator

from home.models import People,Account,CheckPeople
from home.form import PeopleForm
from django.contrib import messages
from django.http import HttpResponse
import os

def writeTofile(data, filename):
    # Convert binary data to proper format and write it on Hard Disk
    with open(filename, 'wb') as file:
        file.write(data)
    

def readBlobData(empId):
    try:
        
        sqliteConnection = sqlite3.connect('db.sqlite3')
        cursor = sqliteConnection.cursor()

        sql_fetch_blob_query = """SELECT * from home_checkpeople where id = ?"""
        cursor.execute(sql_fetch_blob_query, (empId,))
        print(3)
        record = cursor.fetchall()
        for row in record:
            photo = row[5]
           
            photoPath = "C:\\Users\\LENOVO\\PycharmProjects\\pythonProject\\PBL5\\AdminWeb\\image" + str(row[1]) + ".jpg"
            writeTofile(photo, photoPath)
        cursor.close()

    except sqlite3.Error as error:
            print(1)
    finally:
        if sqliteConnection:
            sqliteConnection.close()
            


# Create your views here.
def login(request):
    return render(request, "login/login.html")

def home(request):
    username = request.POST.get("username").strip()
    password = request.POST.get("password").strip()
    try:
        a = Account.objects.get(UserName=username, Password=password)
        p = People.objects.get(ID=a.people_id)
        request.session['people_id'] = p.ID
        request.session['role_id'] = p.RoleID
        q = People.objects.get(pk=p.ID)
        return render(request, 'home/index.html', {"people": q})
    except:
        return render(request, "login/login.html")

def logout(request):
    del request.session['people_id']
    del request.session['role_id']
    return render(request, "login/login.html")

def listUser(request):
    people = People.objects.all().order_by('ID')
    #BUG
    people = list(people)
    for i in people:
        i.image = i.image.decode("utf-8")
    if(request.session['role_id']==1):
        paginator = Paginator(people, 15) # Show 25 contacts per page.
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'tablelist/index.html', {"people": page_obj })
    return HttpResponse('Chuc nang nay chi danh cho admin')
    
    

def detailUser(request,people_id):
    #dulieu = request.POST['people_id']
    # print(people_id)
    q = People.objects.get(pk=people_id)
    q.image = q.image.decode("utf-8")
    return render(request, 'home/index.html', {"people": q})

def updateUser(request,people_id):
    list = People.objects.all().order_by("ID")
    updatePeople = People.objects.get(pk=people_id)
    name = request.POST.get("Name").strip()
    Gender = request.POST.get("Gender").strip()
    if(Gender == "Nam"): Gender = 1
    else: Gender = 0
    roleid = updatePeople.RoleID
    if(roleid == 1):
        RFID = request.POST.get("RFID").strip()
    else:
        RFID = updatePeople.RFID
    age = request.POST.get("Age").strip()

    # if (roleid == "User"):
    #     roleid = 0
    # else:
    #     roleid = 1
    context ={"ID":people_id,"Name":name,"Age":age,"Gender":Gender,"RFID":RFID,"RoleID":roleid}
    form = PeopleForm(context,instance= updatePeople)
    if form.is_valid():
        form.save()
        messages.success(request,"Thành công!")
        if (request.session['role_id'] == 1):
            return render(request, "tablelist/index.html", {"people": list})
        else:
            q = People.objects.get(pk=people_id)
            return render(request, 'home/index.html', {"people": q})
    else:
        return HttpResponse(f"Update không thành công")

def listNotification(request):
    # 
    if(request.session['role_id']):
        # lấy tất cả
        timerecord = CheckPeople.objects.all().order_by('-time')
        
    else:
        timerecord = CheckPeople.objects.filter(id_check= request.session['people_id']).order_by('-time')
    list =[]
    dem = 1
    # for i in timerecord:
    #     if i.id_check == 0:
    #         list.append({"Name": "Không xác định", "Time": i.time, "checkpeople": i.checkpeople,'image': i.image.decode("utf-8") })
    #     else:
    #         p = People.objects.get(pk=i.id_check)
    #         list.append({"Name":p.Name,"Time":i.time,"checkpeople":i.checkpeople,'image': i.image.decode("utf-8") })
    
    for i in timerecord:
        if i.id_check == 0:
            if i.checkpeople == 1:
                list.append({"Name": "Không xác định", "Time": i.time, "checkpeople": i.checkpeople,'image': i.image.decode("utf-8") })
            else:
                list.append({"Name": "Không xác định", "Time": i.time, "checkpeople": i.checkpeople})
        else:
            p = People.objects.get(pk=i.id_check)
            if i.checkpeople == 1:
                list.append({"Name":p.Name,"Time":i.time,"checkpeople":i.checkpeople,'image': i.image.decode("utf-8") })
            else:
                list.append({"Name":p.Name,"Time":i.time,"checkpeople":i.checkpeople})
                
    paginator = Paginator(list, 15) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'notification/notification.html', {"people": page_obj})

def searchUser(request):
    try:
        strSearch = request.POST.get("strSearch").strip()
        people = People.objects.filter(Name__icontains=strSearch).order_by('ID')
        if (request.session['role_id'] == 1):
            return render(request, 'tablelist/index.html', {"people": people})
        # return HttpResponse('Chuc nang nay chi danh cho admin')
    except:
        return HttpResponse('Chuc nang nay chi danh cho admin')

def deleteUser(request, people_id):
    People.objects.filter(ID=people_id).delete()
    people = People.objects.all().order_by('ID')
    return render(request, 'tablelist/index.html', {"people": people})

def statistical(request):
    # 1 : Face
    timesface = CheckPeople.objects.filter(checkpeople = 1).count()
    # 0 : RFID
    timesrfid = CheckPeople.objects.filter(checkpeople = 0).count()
    timestrueface = CheckPeople.objects.filter(checkpeople = 1, ok=1).count()
    timestruerfid = CheckPeople.objects.filter(checkpeople = 0, ok=1).count()
    if (timesface !=0 ):
        percentface = round(timestrueface/timesface *100,2)
    else:
        percentface =0
        
    if (timesrfid !=0 ):
        percentrfid = round(timestruerfid/timesrfid *100,2)
    else:
        percentrfid=0
    # print(statistical)
    return render(request,'statistical/statistical.html',{
        "timesface" : timesface,
        "timesrfid" : timesrfid,
        "timestrueface":timestrueface,
        "timestruerfid":timestruerfid,
        "percentface" : percentface,
        "percentrfid" : percentrfid
    })

templates/home/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link
      rel="apple-touch-icon"
      sizes="76x76"
      href="{% static 'img/apple-icon.png' %}"
    />
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Admin</title>
    <meta
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no"
      name="viewport"
    />
    <!--     Fonts and icons     -->
    <link
      href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200"
      rel="stylesheet"
    />
    <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
      rel="stylesheet"
    />

    <!-- CSS Files -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/paper-dashboard.css' %}" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <!--    <link href="{% static 'demo/demo.css' %}" rel="stylesheet" />-->

    <!-- CSS Files -->
  </head>

  <body class="">
    <div class="wrapper">
      <!--  sidebar   -->

      <!--  End sidebar    -->
      <div class="main-panel">
        <!-- Navbar -->
        {% include 'home/nav.html'%}
        <!-- End Navbar -->
        <div class="sidebar" data-color="white" data-active-color="danger">
          <div class="logo">
            <a href="#" class="simple-text logo-mini">
              <div class="logo-image-small">
                <img src="{% static 'img/logo-small.png' %}" />
              </div>
              <!-- <p>CT</p> -->
            </a>
            <a href="#" class="simple-text logo-normal">
              Admin
              <!-- <div class="logo-image-big">
            <img src="../assets/img/logo-big.png">
          </div> -->
            </a>
          </div>
          {% block sidebarblock%} {% endblock %}
        </div>
        {% block contentblock%} {% endblock %}
        <!-- {% include 'home/footer.html'%} -->
        <!-- footer-->
      </div>
    </div>

    <!--   Core JS Files   -->
    <script src="{% static 'js/core/jquery.min.js' %}"></script>
    <script src="{% static 'js/core/popper.min.js' %}"></script>
    <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
    <!--  Google Maps Plugin    -->
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
    <!-- Chart JS -->
    <script src="{% static 'js/plugins/chartjs.min.js' %}"></script>
    <!--  Notifications Plugin    -->
    <script src="{% static 'js/plugins/bootstrap-notify.js' %}"></script>
    <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
    <script
      src="{% static 'js/paper-dashboard.min.js?v=2.0.1' %}"
      type="text/javascript"
    ></script>
    <!-- Paper Dashboard DEMO methods, don't include it in your project! -->
    <script src="{% static 'demo/demo.js' %}"></script>
  </body>
</html>

templates/home/footer.html
{% load static%}
<footer class="footer footer-black  footer-white ">
        <div class="container-fluid">
          <div class="row">
            <nav class="footer-nav">
              <ul>
                <li><a href="#" target="_blank">Response</a></li>
                <li><a href="#" target="_blank">Blog</a></li>
                <li><a href="#" target="_blank">Licenses</a></li>
              </ul>
            </nav>
            <div class="credits ml-auto">
              <span class="copyright">
                © <script>
                  document.write(new Date().getFullYear())
                </script>
              </span>
            </div>
          </div>
        </div>
      </footer>

templates/home/index.html
<!--
=========================================================
* Paper Dashboard 2 - v2.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/paper-dashboard-2
* Copyright 2020 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
{% extends 'home/base.html'%} {% load static%} {% block sidebarblock%}
<div class="sidebar-wrapper">
  <ul class="nav">
    {% if request.session.role_id == 1 %}
    <li>
      <a href="{% url 'home:statistical' %}">
        <i class="nc-icon nc-bank"></i>
        <p>Thông kê</p>
      </a>
    </li>
    {% endif %}
    <li>
      <a href="{% url 'home:notification' %}">
        <i class="nc-icon nc-bell-55"></i>
        <p>LỊch SỬ</p>
      </a>
    </li>
    <li class="active">
      <a href="{% url 'home:detail' request.session.people_id %}">
        <i class="nc-icon nc-single-02"></i>
        <p>thông tin người dùng</p>
      </a>
    </li>
    {% if request.session.role_id == 1 %}
    <li>
      <a href="{% url 'home:tablelist' %}">
        <i class="nc-icon nc-tile-56"></i>
        <p>Người dùng</p>
      </a>
    </li>
    {% endif%}
  </ul>
</div>
{% endblock %} {% block contentblock%}

<!--   Content   -->
<div class="content">
  <div class="row">
    <div class="col-md-4">
      <div class="card card-user">
        <div class="image">
          <img src="{% static 'img/damir-bosnjak.jpg' %}" alt="..." />
        </div>
        <div class="card-body">
          <div class="author">
            <a href="#">
              <img
                class="avatar border-gray"
                style="height: 240px; width: 280px"
                src="data:image/png;base64,{{people.image}}"
                alt="..."
              />

              <h5 style="font-size: 30px; margin-bottom: 20px" class="title">{{people.Name}}</h5>
            </a>
            <p class="description"></p>
          </div>
          <p style="font-size: 26px" class="description text-center">
            {% if people.RoleID == 1 %} Admin {%else%} User {% endif %}
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="card card-user">
        <div class="card-header">
          <h5 class="card-title">Chỉnh sửa</h5>
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'home:update' people.ID %}">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-5 pr-1">
                <div class="form-group">
                  <label>Role</label>
                  <input
                    type="text"
                    name="RoleID"
                    class="form-control"
                    placeholder="Company"
                    disabled
                    value="{% if people.RoleID == 1 %}Admin{%else%}User{% endif %}"
                  />
                </div>
              </div>
              <div class="col-md-5 pr-1">
                <div class="form-group">
                  <label>ID</label>
                  <input type="text" name="ID" class="form-control" placeholder="ID" disabled value="{{people.ID}}" />
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-10">
                <div class="form-group">
                  <label>Tên</label>
                  <input type="text" class="form-control" name="Name" placeholder="Company" value="{{people.Name}}" />
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-4 pr-1">
                <div class="form-group">
                  <label>Tuổi</label>
                  <input type="text" class="form-control" name="Age" placeholder="Age" value="{{people.Age}}" />
                </div>
              </div>
              <div class="col-md-4 px-1">
                <div class="form-group">
                  <label>Giới tính</label>
                  <input
                    type="text"
                    class="form-control"
                    name="Gender"
                    placeholder="Country"
                    value="{% if people.Gender == 1  %}Nam{% else %}Nữ{%endif%}"
                  />
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-10">
                <div class="form-group">
                  <label>RFID</label>
                  {% if request.session.role_id == 1 %}
                  <input type="text" name="RFID" class="form-control" placeholder="RFID" value="{{people.RFID}}" />
                  {% else %}
                  <input
                    type="text"
                    name="RFID"
                    class="form-control"
                    placeholder="RFID"
                    value="{{people.RFID}}"
                    disabled
                  />
                  {% endif %}
                </div>
              </div>
            </div>
            <div class="row">
              <div class="update ml-auto mr-auto">
                <button type="submit" class="btn btn-primary btn-round">Cập nhập</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End Content -->
{% endblock %}

templates/home/nav.html
<nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <div class="navbar-toggle">
        <button type="button" class="navbar-toggler">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </button>
      </div>
      <a class="navbar-brand" href="javascript:;">Admin page</a>
    </div>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navigation"
      aria-controls="navigation-index"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navigation">
      <!-- <form action="" method="post">
        <div class="input-group no-border">
          <input type="text" value="" class="form-control" placeholder="Search...">
          <div class="input-group-append">
            <div class="input-group-text">
              <i class="nc-icon nc-zoom-split"></i>
            </div>
          </div>
        </div>
      </form> -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link btn-magnify" href="javascript:;">
            <i class="nc-icon nc-layout-11"></i>
            <p>
              <span class="d-lg-none d-md-block">Stats</span>
            </p>
          </a>
        </li>
        <li class="nav-item btn-rotate dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="http://example.com"
            id="navbarDropdownMenuLink"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            <i class="nc-icon nc-bell-55"></i>
            <p>
              <span class="d-lg-none d-md-block">Some Actions</span>
            </p>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <!--                  <i class="nc-icon nc-settings-gear-65"></i>Log out-->
          <button style="margin-top: 10px; background-color: #f4f3ef; border: none; height: 10px">
            <a style="width: 100%" href="{% url 'home:logout'%}">Log out</a>
          </button>
          <p>
            <span class="d-lg-none d-md-block">Account</span>
          </p>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/home/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/home/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>